version: "3"
services: 
    node-app:
        build: .
        ports: 
            - 3000:3000
        depends_on: 
            - mysql
        networks: 
            - node_network

    mysql:
        image: mysql:5.7
        restart: always
        environment: 
            MYSQL_ROOT_PASSWORD: abror123
        networks: 
            - node_network
    
    phpmyadmin:
        image: phpmyadmin
        restart: always
        environment: 
            PMA_HOST: mysql
        ports: 
            - 8082:80
        networks: 
            - node_network 

networks: 
    node_network:
        name: node_network



